- name: "IT Computer Setup"
  hosts: localhost
  connection: local
  tasks:

  - name: "Install XCode CLI"
    shell: xcode-select --install

  - name: "Install Homebrew"
    shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"